import datetime
import uuid

from pydantic import BaseModel, Field


class EventEnvelope[T: BaseModel](BaseModel):
    """Standardized event envelope wrapping all platform domain events."""

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str
    timestamp: datetime.datetime = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC)
    )
    correlation_id: str
    version: str = "1.0.0"
    payload: T


class CitizenReportSubmitted(BaseModel):
    """Payload representing a newly submitted report by a citizen (EVT-101)."""

    citizen_id: str
    report_id: str
    text_content: str
    media_urls: list[str] = Field(default_factory=list)


class IssueValidated(BaseModel):
    """Payload representing a validated issue inside the state machine (EVT-201)."""

    issue_id: str
    title: str
    description: str
    category: str
    reported_at: datetime.datetime


class RecommendationGenerated(BaseModel):
    """Payload representing advice generated by AI platform service (EVT-301)."""

    recommendation_id: str
    issue_id: str
    suggested_category: str
    suggested_department: str
    confidence_score: float


class AccessLogGenerated(BaseModel):
    """Payload representing compliance audit access record (EVT-602)."""

    log_id: str
    actor_id: str
    action: str
    resource: str
    success: bool
